== Creating a template for a Virtual Machine (*INTERNAL ONLY*)
This section describes the process for creating a KVM template for use in projects.

A template is a fully pre-configured operating system image that can used to deploy KVM virtual machines.
By building one or more KVM templates, you can deploy multiple virtual machine images in your environment.

Terms and conventions:

* A clone is a copy of an existing virtual machine. The existing virtual machine is called the parent of the clone. When the cloning operation is complete, the clone is a separate virtual machine.
* A snapshot is a copy of the virtual machine's disk file  at a given point in time.  Snapshots provide a change log for the virtual disk and are used to restore a VM to a particular point in time when a failure or system error occurs.
* A template is a master copy of a virtual machine that can be used to create many clones.

=== Disk Format: Raw vs Qcow2
let's talk about VM disk formats, since libvirt snapshots can only be performed on certain type of disk formats. There are several types of VM disk formats, but the most common are raw and qcow2 (copy-on-write). Raw disks are presented as-is to the VM without any disk layering and do not support snapshots, whereas qcow2 disks support a range of special features including snapshots, compression and encryption.

Raw disks have better I/O performance than qcow2 because the VM disk space is pre-allocated before the VM is created, as opposed to qcow2, where VM disk space is thinly provisioned and allocated on-the-go as the VM requires it. If you create a VM with a raw disk of 10 GB, you‟ll see that the disk image size for the VM will be exactly 10 GB, whereas for a VM with a qcow2 disk the actual file size will be a fraction of 10 GB (say 2-3 GB) and it will grow as you occupy disk space inside the VM.

Snapshots can be considered a “backup” of a VM's disk, although no actual bits are copied or backed up. The system simply remembers the state of a VM and takes advantage of the copy-on-write capabilities of qcow2. So snapshots are simply a record of where bits stood at a given point in time, not an actual copy of the bits.


To generate the base vm http://packer.io[packer] will be used to create the image.

=== Packer
Packer is a tool for creating machine and container images for multiple platforms from a single source configuration.

Since the solution will be primarily generating a KVM based image, packer must be installed and used on a linux host.

[source,bash]
----
$ wget -qO- -O tmp.zip https://releases.hashicorp.com/packer/0.10.1/packer_0.10.1_linux_amd64.zip && unzip tmp.zip && rm tmp.zip
----

Once packer is available it can be used as follows:

[source,bash]
----
# start the installation
packer build -only=centos-7-qemu-qcow2 centos7.json

# shrink the image size
qemu-img convert -c -f qcow2 -O qcow2 -o cluster_size=2M target/centos-7-qemu.qcow2 target/centos-7-qemu-compressed.qcow2
----

At this point we will have a default VM, compressed in qcow2 format that can be used as a template.



Tasks:

* Create base vm with dependencies installed to clone from into a template
* Create configurations for each of the server configs; small(8G), medium(16), large(32) and extra-large(64)


Reading:

* http://ostolc.org/kvm-clone-guests-from-template-image.html
* http://linuxplayer.org/2011/06/create-new-kvm-guest-from-template
* http://www.unixarena.com/2015/12/how-to-clone-a-kvm-virtual-machines-and-reset-the-vm.html
* https://nwlinux.com/clone-raw-img-kvm-virtual-machine-on-centos-7-x/
* http://rohitchauhanit.blogspot.co.uk/2015/11/kvm-snapshot-and-clone.html
